name: Deploy to Google App Engine
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.APPENGINE_DEPLOY_SA_KEY_JSON }}'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'